drop table approve;

create table approve(
	APPR_CODE		NUMBER			PRIMARY KEY,
	M_CODE			VARCHAR2(50),
	APPR_TITLE		VARCHAR2(200),
	APPR_CONTENT	VARCHAR2(1000),
	FIRST_CODE		VARCHAR2(50),
	SECOND_CODE		VARCHAR2(50),
	THIRD_CODE		VARCHAR2(50),
	APPR_FILE		VARCHAR2(500),
	APPR_ORIGIN		VARCHAR2(500),
	APPR_STAT		NUMBER,
	APPR_DATE		VARCHAR2(500),
	APPR_VAL		NUMBER

);


