CREATE TABLE SCHEDULE(
SCH_TITLE VARCHAR2(100),
SCH_STARTDATE DATE,
SCH_STARTTIME DATE,
SCH_ENDDATE DATE,
SCH_ENDTIME DATE,
SCH_PARTICIPANT VARCHAR2(200),
SCH_PLACE VARCHAR2(100),
SCH_COLOR VARCHAR2(40),
SCH_OPEN VARCHAR2(10),
SCH_CONTENT VARCHAR2(500)
);

SELECT * FROM SCHEDULE;

DROP TABLE SCHEDULE;